packages:
  - 'package/*'
  - 'package-legacy/*'
  - 'workspace'
overrides:
  '@lickle/legacy-cli': link:package-legacy/cli
  '@lickle/legacy-api': link:package-legacy/api
  '@lickle/api': link:package/api
  '@lickle/cli': link:package/cli
